version: "3"
services:
  app:
    build: ./api-service
    container_name: tioapp
    image: rliapp
    restart: always
    volumes:
      - ./api-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:5000
    expose:
      - 5000
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306

  db:
    build: ./db-service
    restart: always

  webserver:
    image: nginx:mainline-alpine
    container_name: tiowebserver
    restart: unless-stopped
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./nginx-conf/:/etc/nginx/conf.d/
    depends_on:
      - app
